# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96963cf0486bd57d632997f8263ccf4833e03f1aebe46bfc8d0e2c71e65334dcd2f62ccecc89919da7e537639034ae890c1f954e3c9acd36cd18c01d0a0c7ff4

test:
  secret_key_base: 86c512a28e3c0346448c12fa2cf4e2620bafc164cc4c0d67e5cd864db8b6ae3b01afd0f3850ff5b5f16fd4ecf11c5c0aad83fe0dc055210addde7d65d408df99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
